# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure 2 do |config|

  USER = "vagrant"
  ROOT = ".."
  COURSE = "cs3281"
  BOX = "#{COURSE}_ubu1404"
  IMG = "box-cutter/ubuntu1404-desktop"

  config.ssh.port = "2222"
  config.ssh.guest_port = "22"
  config.ssh.forward_agent = true

  # Vagrant Box template
  config.vm.box = IMG

  # Vagrant Box name
  config.vm.define BOX.to_sym

  # Directory shared between host and guest.
  config.vm.synced_folder "#{ROOT}", "/home/#{USER}/#{COURSE}"

  config.vm.provider "virtualbox" do |vb|
  	vb.name = BOX
    vb.gui = false # change me to false to run in headless mode
    # tweak as necessary
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end

  # Bootstrap puppet via shell provisioner.
  config.vm.provision "shell", path: "puppet/bootstrap.sh"

  # Execute the main configuration.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "init.pp"
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
  end

end
