# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure 2 do |config|

  USER = "vagrant"
  ROOT = ".."
  COURSE = "cs3281"
  BOX = "#{COURSE}_ubu1404"
  IMG = "box-cutter/ubuntu1404-desktop"

  config.ssh.port = "2222"
  config.ssh.guest_port = "22"
  config.ssh.forward_agent = true

  # Vagrant Box template
  config.vm.box = IMG

  # Vagrant Box name
  config.vm.define BOX.to_sym

  # Shared root of host course-info repo with guest
  config.vm.synced_folder "#{ROOT}", "/home/#{USER}/#{COURSE}"

  config.vm.provider "virtualbox" do |vb|

  	vb.name = BOX

    # required for 64-bit vm
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]

    # 3d acceleration has historically been unstable
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]

    # tweak for individual computer
    vb.gui = true # change me to false to run in headless mode
    vb.customize ["modifyvm", :id, "--memory", "2096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]

  end

  # Bootstrap puppet via shell provisioner.
  config.vm.provision "shell", path: "puppet/bootstrap.sh"

  # Execute the main configuration.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "init.pp"
    puppet.manifests_path = "puppet/manifests"
  end

end
